repos:
#- repo: https://github.com/psf/black
#  rev: 23.3.0
#  hooks:
#    - id: black
#      args: [--quiet]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.290
  hooks:
    - id: ruff
