name: qt_viz_tests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true
on:
    pull_request:
    push:
      branches: main

jobs:
  raw-viz-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |  # use MNE main to ensure test files are available
          set -e
          python -m pip install --upgrade pip
          git clone --depth=1 https://github.com/marsipu/mne-python.git
          pushd mne-python
          git checkout pg_test
          popd
          python -m pip install -e ./mne-python
          python -m pip install -r requirements.txt
        shell: bash
      - run: |
          set -e
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1
        shell: bash
        name: Setup OpenGL on Windows
        if: runner.os == 'Windows'
      - run: ./tools/setup_xvfb.sh
        name: Setup xvfb on Linux
        working-directory: mne-python
        if: runner.os == 'Linux'
      - name: Run MNE-Tests
        run: |
          pwd
          mnePath=$(python -c "import mne; print(mne.__path__[0])")
          mkdir ./_temp_tests
          cp $mnePath/viz/tests/test_raw.py ./_temp_tests/test_raw.py
          pytest
          rm -r ./_temp_tests
        shell: bash

  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: flake8